### PR TITLE
worflow for new contributors

### LINKED ISSUE #309: Feature request : Workflow for greeting new contributors with welcome memes
### Proposed Solution:

* Recognition of First Contribution: Identify and celebrate the first contribution made by a new contributor to the project.

* Selection of Welcome Meme: Randomly select a welcome meme from a collection of friendly and inclusive images that align with our project's culture.

* Automated Comment: Automatically post the selected welcome meme as a comment on the new contributor's pull request or issue.

* Friendly Message: Accompany the meme with a friendly and welcoming message, expressing gratitude for their contribution and inviting them to further engage with the community.

### PR DESCRIPTION
**Pull request by vivekreddy049**
fixes #309

### CODE REVIEW

**Comment by Tushar98644** [comment]
> fixes #309

Instead of choosing the memes from just 3 of these , use an API to dynamically fetch the memes . Also mention the things that need to be added such as repo secrets , permissions etc

**Comment by vivekreddy049** [comment]
fine,can you mention the api's

**Comment by Tushar98644** [comment]
> fine,can you mention the api's

you can use this one : https://rapidapi.com/webknox/api/jokes/ , signup to rapidapi and generate an api key

**Comment by Tushar98644** [comment]
@vivekreddy049 any updates

**Comment by vivekreddy049** [comment]
i ended making up a github action without a random meme. iam not so familiar with fetching memes with api

**Comment by vivekreddy049** [comment]
don't you need this @Tushar98644

**Pull request closed without merging**
