### PR TITLE
Fix 306: Add responsive table

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by Tushar98644** [comment]
@Dhruv127 The table looks ok . Just update the pending approval , icon and welcome text , then you are pretty much done

**Comment by Dhruv127** [comment]
can you be specific, about how should pending approval, icon, and welcome text be align? I do have to make some changes in that too .. for smaller screen sizes. But if you need anything else do tell me.

**Comment by Tushar98644** [comment]
> can you be specific, about how should pending approval, icon, and welcome text be align? I do have to make some changes in that too .. for smaller screen sizes. But if you need anything else do tell me.

Nothing in particular , just make sure the UI looks clean for smaller devices. Don't place them horizontally and maybe add some animations

**Comment by Tushar98644** [comment]
@Dhruv127 The text in the fields should not overlap , add some margin between the `search` and `action` tabs <br />
Screenshot 2023-10-14 at 4 30 38 PM

**Comment by Dhruv127** [comment]
I am not facing the above issue at any dimensions
Screenshot (207)
. Can you tell , at what point exactly you are facing this problem?

**Comment by Tushar98644** [comment]
> I am not facing the above issue at any dimensions Screenshot (207) . Can you tell , at what point exactly you are facing this problem?

search for any project using the search box , the texts overlap

**Comment by Dhruv127** [comment]
Screenshot (217)
i couldn't find out , it would be good ig .. if you can share more details

**Comment by Dhruv127** [comment]
Have added the space, if you don't find any issues, kindly merge the PR.

**Comment by Tushar98644** [comment]
> Have added the space, if you don't find any issues, kindly merge the PR.

Screenshot 2023-10-18 at 8 05 00 PM

The issue is still there for majority of the mobile devices, but it's a small fix, and the rest of the things seem fine so merging the code. Thanks for the contribution!

**Pull request merged**
